name: Deploy Lambda Functions

on:
  push:
    branches: [main]
    paths:
      - "src/functions/**"
      - ".github/workflows/deploy-lambdas.yml"
      - ".github/workflows/deploy-lambdas-env.yml"
  workflow_dispatch:
    inputs:
      deploy-users:
        description: "Deploy Users Lambda"
        type: boolean
        default: true
      deploy-authorizer:
        description: "Deploy Authorizer Lambda"
        type: boolean
        default: true

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/deploy-lambdas-env.yml
    with:
      environment: dev
      deploy-users: ${{ github.event_name != 'workflow_dispatch' || inputs.deploy-users }}
      deploy-authorizer: ${{ github.event_name != 'workflow_dispatch' || inputs.deploy-authorizer }}
    secrets: inherit

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-dev
    uses: ./.github/workflows/deploy-lambdas-env.yml
    with:
      environment: prod
      deploy-users: ${{ github.event_name != 'workflow_dispatch' || inputs.deploy-users }}
      deploy-authorizer: ${{ github.event_name != 'workflow_dispatch' || inputs.deploy-authorizer }}
    secrets: inherit
